Reverting my 4156 bug fix. It worked great, but I tried building other arches to make sure it didn't break anything else, and BOOM!!!  I left my changes, but commented them out until I can figure out why this broke.
  modereq.cpp:(.text+0x231): undefined reference to `__cxa_guard_acquire'
  modereq.cpp:(.text+0x24b): undefined reference to `__cxa_guard_release'