Cross-compile testplat with g++ instead of cc
Using cc on CentOS 6 fails with error:
 /tmp/cc0k5oTG.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' collect2: ld returned 1 exit status
Using g++ is more common on current cross-compile targets but eventually this
might require separate configure variable (or phasing out testplat completely)